### ISSUE TITLE
May I have the all dataset?

### ISSUE THREAD

**Issue by Azure-Whale** [ENCASEH2020/hatespeech-twitter#4]
Hi AndyFou!

I'm working on some own project and I hope that I may use your full dataset bc most tweet ids were unavailable and I couldn't fetch any tweets from it. I'm wondering if you can share full dataset(text-label) if possible? Thank you in advance!

Best,
Kazuo

**Comment by bhumikabhatia** [comment]
Hi, same here. I am working on a research project and if you could kindly share the full dataset it would be of great help. Thanks!

**Comment by qiqingh** [comment]
> Hi AndyFou!
> 
> I'm working on some own project and I hope that I may use your full dataset bc most tweet ids were unavailable and I couldn't fetch any tweets from it. I'm wondering if you can share full dataset(text-label) if possible? Thank you in advance!
> 
> Best,
> Kazuo

You can apply for a twitter developer account, then can retrieve the full dataset by the tweet ID in each row

**Comment by Azure-Whale** [comment]
Thank you for answering! That's exactly what I am trying to do. However, I
cannot retrieve data from most of these ids anymore, only a few of them can
be obtained. I guess some of them are unavailable now. This may sometimes
happen to some other tweet datasets. Have you retrieved this dataset
successfully recently?

qiqingh <notifications@github.com> 于2020年11月8日周日 上午11:04写道：

**Comment by AndyFou** [comment]
Hi, could you please email me at a[.]m[.]founta[@]gmail.com? So you can agree to our terms and I can give you access to the full dataset.

**Comment by dkhaval** [comment]
Hii, can i get the full dataset with text as i m working on some own project . I tried fetching the data from twitter but most of the tweets id ka not working or the it might be deleted. Plzzzzz
